apiVersion: apps/v1
kind: Deployment
metadata:
  name: niova-csi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niova-csi-cont
  template:
    metadata:
      labels:
        app: niova-csi-cont
    spec:
      nodeName: k8s-worker1
      serviceAccountName: niova-csi-sa
      hostPID: true
      containers:
        - name: niova-csi
          image: paro1618/niova-csi:controller
          securityContext:
            privileged: true
            capabilities:
              add:
                - CAP_SYS_ADMIN
                - CAP_SYS_RESOURCE
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - ulimit -l unlimited && exec /opt/niova/niova-block-csi-controller -driver-name=csi.niova.com -version=0.1.0 -node-id=$(NODE_ID) -endpoint=unix:///csi/custom2.sock -nisd-config=/var/lib/niova-csi/nisd-config.yml -volume-tracking=/var/lib/niova-csi/volumes.yml
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          terminationMessagePath: /tmp/termination-log
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
            - name: niova-var-dir
              mountPath: /var/niova
            - name: niova-block
              mountPath: /niova-block
            - name: host-dev
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: host-sys
              mountPath: /sys
            - name: host-mount
              mountPath: /run
            - name: lib-modules
              mountPath: /lib/modules
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/plugins
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
            - name: mount-kb
              mountPath: /var/lib/kubelet
            - name: nisd-config
              mountPath: /var/lib/niova-csi
              mountPropagation: Bidirectional

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          args:
            - "--csi-address=/csi/custom2.sock"
            - "--v=5"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.4.0
          args:
            - "--csi-address=/csi/custom2.sock"
            - "--v=5"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi 
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.niova.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: niova-var-dir
          hostPath:
            path: /var/niova
            type: DirectoryOrCreate
        - name: niova-block
          hostPath:
            path: /root/niova-block
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-mount
          hostPath:
            path: /run
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet/plugins
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
        - name: mount-kb
          hostPath:
            path: /var/lib/kubelet
        - name: nisd-config
          hostPath: 
            path: /var/lib/niova-csi

