apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.niova.com
spec:
  attachRequired: true
  volumeLifecycleModes:
    - Persistent
  podInfoOnMount: true
  fsGroupPolicy: File
  requiresRepublish: false
