apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: niova-csi-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: niova-csi-node
  template:
    metadata:
      labels:
        app: niova-csi-node
    spec:
      serviceAccountName: niova-csi-sa
      hostPID: true
      containers:
        - name: niova-csi
          image: paro1618/niova-csi:node-v4
          securityContext:
            privileged: true
            capabilities:
              add:
                - CAP_SYS_ADMIN
                - CAP_SYS_RESOURCE
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - ulimit -l unlimited && exec /opt/niova/niova-block-csi-node -driver-name=csi.niova.com -version=0.1.0 -node-id=$(NODE_ID) -endpoint=unix:///csi/custom.sock
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NIOVA_GOSSIP_PATH
              value: "/etc/niova/gossipNodes"
            - name: NIOVA_GOSSIP_KEY
              value: "5c587ba3-0f41-4476-b444-ffc6bba95ff0"
          terminationMessagePath: /tmp/termination-log
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
            - name: niova-var-dir
              mountPath: /var/niova
              mountPropagation: Bidirectional
            - name: host-dev
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: host-sys
              mountPath: /sys
            - name: host-mount
              mountPath: /run
              mountPropagation: Bidirectional
            - name: lib
              mountPath: /lib
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: mount-kb
              mountPath: /var/lib/kubelet
            - name: nisd-config
              mountPath: /etc/niova
              mountPropagation: Bidirectional
            - name: sbin-dir
              mountPath: /usr/sbin
              mountPropagation: HostToContainer
            - name: bin-dir
              mountPath: /bin
              mountPropagation: HostToContainer
            - name: usr-bin
              mountPath: /usr/bin
              mountPropagation: HostToContainer

        - name: driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
          args:
            - "--csi-address=/csi/custom.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.niova.com/custom.sock"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration

      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.niova.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: niova-var-dir
          hostPath:
            path: /var/niova
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-mount
          hostPath:
            path: /run
        - name: lib
          hostPath:
            path: /lib
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet/plugins
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
        - name: mount-kb
          hostPath:
            path: /var/lib/kubelet
        - name: nisd-config
          hostPath:
            path: /etc/niova
        - name: sbin-dir
          hostPath:
            path: /usr/sbin
        - name: bin-dir
          hostPath:
            path: /bin
        - name: usr-bin
          hostPath:
            path: /usr/bin

